Module4 task1
htmlacademy-react/96091-six-cities-12 pull request #5
Opened 2023-03-27 08:45 UTC by SergViktKobzev

2023-03-28 00:30 UTC, AlexMasterov requested changes

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/components/offer-card-list-by-city/offer-card-list-by-city.tsx
> +export default function OfferCardListByCity({favoriteOffers, city}: OfferCardFavoritesProps): JSX.Element {
`OfferCardListByCity`

Желательно (пере)назвать компонент без `By`.

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/components/offer-card-list-by-city/offer-card-list-by-city.tsx
> +  const favoriteOffersByCity: Offers = favoriteOffers.filter((offer) => offer.city.name === city);
favoriteOffers`ByCity`

[Б10](https://up.htmlacademy.ru/react/12/criteries#b10) 
> Массивы названы существительными во множественном числе или с использованием венгерской нотации (указанием типа в названии)

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/components/offer-card-list-by-city/offer-card-list-by-city.tsx
> +                  <span style={{width: `${String(offer.rating * 20)}%`}}></span>
${String(offer.rating * `20`)}%

[Д5](https://up.htmlacademy.ru/react/12/criteries#d5)
> В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа

Тоже самое: (дублирование)

https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/components/offer-card/offer-card.tsx#L33

Желательно для форматирование создать отдельную функцию.

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/components/offer-card-nearby/offer-card-nearby.tsx
> +        null}
<details>
<summary>components/offer-card-city/offer-card-city.tsx</summary>

https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/components/offer-card-city/offer-card-city.tsx#L17-L26
</details>

<details>
<summary>components/offer-card-list-by-city/offer-card-list-by-city.tsx</summary>

https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/components/offer-card-list-by-city/offer-card-list-by-city.tsx#L16-L25
</details>

<details>
<summary>components/offer-card-nearby/offer-card-nearby.tsx</summary>

https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/components/offer-card-nearby/offer-card-nearby.tsx#L12-L21
</details>

Разметка дублируется.

Желательно перенести эту разметку в `components/offer-card/offer-card.tsx`.

> Похоже, что на момент создания компонентов ты не знал про фрагмент `<>`, чтобы создать род. узел для разметки компонента (?)

> См. снова https://github.com/htmlacademy-react/96091-six-cities-12/pull/3#discussion_r1127749006

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/components/reviews-form/reviews-form.tsx
> +        {Array.from({length: RATING_STARS_COUNT}, (_, index) => (
<details>
<summary>components/reviews-form/reviews-form.tsx</summary>

https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/components/reviews-form/reviews-form.tsx#L15
https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/components/reviews-form/reviews-form.tsx#L23-L24
https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/components/reviews-form/reviews-form.tsx#L28
https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/components/reviews-form/reviews-form.tsx#L30
</details>

`Array.from({length: RATING_STARS_COUNT}`, (_, index) => (

 title={`RATING_TITLES[index]`} 

Массив значений рейтинга и титулов можно создать вне компонента, один раз, и далее (пере)использовать внутри с `.map`. Не менее важно сделать его удобным для разметки, чтобы в ней не использовать вычисления с константами и т.п.

> Такой массив можно записать в формате константы

Пример:

```js
RATING_TITLES.map(({ rating, title }) => 
```

**JS2**-Д19
> Массивы и объекты, содержимое которых вычисляется, собираются один раз, а после этого только переиспользуются

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/components/reviews-form/reviews-form.tsx
> +          <React.Fragment key={index}>
<`React.Fragment` key={index}>

См. [React.Fragment](https://ru.reactjs.org/docs/react-api.html#reactfragment):
> Вы также можете использовать его сокращённый синтаксис `<></>`

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/components/reviews-form/reviews-form.tsx
> +  const [NewReview, setNewReview] = useState({
`N`ewReview

[Б5](https://up.htmlacademy.ru/react/12/criteries#b5) 
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации `camelCase`

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/pages/layout/layout.tsx
> +      <li className="header__nav-item user">
<details>
<summary>pages/layout/layout.tsx</summary>

https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/pages/layout/layout.tsx#L11-L12
https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/pages/layout/layout.tsx#L29-L30
</details>

Разметка снова дублируется.

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/pages/room-page/room-page.tsx
> +  const offer = offers.find((item) => String(item.id) === params.id);
.find((item) => `String(item.id)` === params.id);

Лучше (и эффективней) до цикла один раз привести `params.id` к числу, чем приводить `item.id` к строке на _каждой_ итерации.

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/pages/room-page/room-page.tsx
> +  if (offer === undefined) {
if (offer `=== undefined`) {

🤔
```js
const offer = offers.find((item) => String(item.id) === params.id) ?? null;

if (offer === null) {
```
> `null` = no (_object_) value

либо просто, через (неявное) приведение к булевому значению:

```js

if (!offer) {
```
**JS2**-Д10
> В проекте не должно быть избыточных проверок

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/pages/room-page/room-page.tsx
> +  const propertyImages = images.slice(0, 6);
images.slice(0, `6`)

[Д5](https://up.htmlacademy.ru/react/12/criteries#d5) 
> В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/pages/room-page/room-page.tsx
> +                  `${bedrooms} Bedroom`}
(bedrooms > `1`)

_Могут_ придраться.

> \+ неудачное форматирование `? :` + дублирование кода

[Д5](https://up.htmlacademy.ru/react/12/criteries#d5) 
> В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/pages/room-page/room-page.tsx
> +                  'property__avatar-wrapper property__avatar-wrapper--pro user__avatar-wrapper' :
Форматирование:

```js
isPro 
 ?
 :
```

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/pages/room-page/room-page.tsx
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/228095757-23eb7363-fd28-4e90-9d59-194064d3b98a.png)

</details>

См. ТЗ:
> Рейтинг. Оценка выводится в виде закрашенных звезд. Максимальное количество звёзд — 5. Оценка округляется до ближайшего целого. **Например, оценка 3.1 округляется до 3-х**. Оценка 4.5 округляется до 5.

2023-03-28 00:30 UTC, AlexMasterov commented on project/src/pages/room-page/room-page.tsx
> +
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/228096000-7967ddeb-0063-4eee-9d72-89e6d3c8677f.png)

![image](https://user-images.githubusercontent.com/700213/228096035-554ee34d-bf56-409c-afd1-d8252666535e.png)

</details>

<details>
<summary>Ожидание (markup/property.html)</summary>

![image](https://user-images.githubusercontent.com/700213/228096130-9915cd9d-2e74-4e63-8826-7928391be8a9.png)

</details>

Нужно поправить разметку.

2023-03-28 00:34 UTC, AlexMasterov commented on project/src/components/offer-card-nearby/offer-card-nearby.tsx
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/228096647-e28a8423-8652-4e64-bfc7-70c52a68f824.png)

</details>

Желательно поправить разметку.

2023-03-28 00:51 UTC, AlexMasterov commented on project/src/pages/layout/layout.tsx
> +
https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/pages/layout/layout.tsx#L8
https://github.com/htmlacademy-react/96091-six-cities-12/blob/b5b0747a32b312d8c1c5768be641dad215eeb15e/project/src/pages/layout/layout.tsx#L41

В одном модуле находится два компонента.

~Б21

2023-04-05 08:09 UTC, SergViktKobzev commented on project/src/components/offer-card-nearby/offer-card-nearby.tsx
> +        null}
Что именно здесь считается дублированием разметки? Вопрос уточню в telegram

2023-04-05 08:10 UTC, SergViktKobzev commented on project/src/components/reviews-form/reviews-form.tsx
> +        {Array.from({length: RATING_STARS_COUNT}, (_, index) => (
Не понимаю как это реализовать:(

2023-04-05 08:13 UTC, SergViktKobzev commented on project/src/components/reviews-form/reviews-form.tsx
> +          <React.Fragment key={index}>
У меня вот такая запись выдает ошибку <key={index}></>. Может как-то по другому надо это реализовать?

2023-04-05 16:23 UTC, AlexMasterov commented on project/src/components/offer-card-city/offer-card-city.tsx
> +    <article onMouseOver={offerCardMouseOverHandler} className="cities__card place-card">
onMouseOver={`offerCardMouseOverHandler`}

Желательно использовать `handle*`.

[Д2.](https://up.htmlacademy.ru/react/12/criteries#d2) 
> Методы-обработчики классов названы через `handle`

> `handle` +` название объекта` + `название события`

> См. [пример в демо проекте](https://github.com/htmlacademy-react/guess-melody-12/blob/master/project/src/pages/auth-screen/auth-screen.tsx#L44) (на самом деле там тоже неразбериха, никак не исправят)

2023-04-05 16:23 UTC, AlexMasterov commented on project/src/components/offer-card-container/offer-card-container.tsx
> +        <b className="places__found">{offerCount} places to stay in Amsterdam</b>
https://github.com/htmlacademy-react/96091-six-cities-12/blob/554c930e78ffc529d609b970665f78ca6800de6a/project/src/index.tsx#L18-L19

С добавлением `offers` можно отказаться от `offerCount` и брать актуальное значение из `offers.length`.

2023-04-05 16:24 UTC, AlexMasterov commented on project/src/components/reviews-form/reviews-form.tsx
> +        {Array.from({length: RATING_STARS_COUNT}, (_, index) => (
В примере показал ожидание по (интерфейсу) использованию:

```js
RATING_TITLES.map(({ rating, title }) => 
```

На основе этого можно набросать структуру: (сначала вручную)

<details>
<summary>Пример</summary>

```js
  const RATING_TITLES = [
    { rating: 1, title: 'terribly' },
    { rating: 2, title: 'badly' },
    { rating: 3, title: 'not bad' },
    { rating: 4, title: 'good' },
    { rating: 5, title: 'perfect' },
  ];
```
```jsx
{RATING_TITLES.map(({ rating, title }) => (
    <React.Fragment key={rating}>
      <input
        onChange={(evt) => {
          setNewReview({...newReview, rating: Number(evt.target.value)});
        }}
        className="form__rating-input visually-hidden"
        name="rating"
        value={rating}
        id={`${rating}-stars`}
        type="radio"
        checked={newReview.rating === rating}
      />
      <label
        htmlFor={`${rating}-stars`}
        className="reviews__rating-label form__rating-label"
        title={title}
      >
        <svg className="form__star-image" width="37" height="33">
          <use xlinkHref="#icon-star"></use>
        </svg>
      </label>
    </React.Fragment>
  ))}
```
> Значение `newReview.rating` должно быть типа `number`
</details>

В примере массив `RATING_TITLES` создан вручную, но его также можно сгенерировать с помощью кода, на основе перечислений и прочих констант. Сейчас значения из массива используются только в помощью генерации разметки одного компонента и для них больше нет логики, отчего создания отдельных структур и сама генерация выглядит избыточной.

2023-04-05 16:24 UTC, AlexMasterov commented on project/src/components/reviews-form/reviews-form.tsx
> +          <React.Fragment key={index}>
> Может как-то по другому надо это реализовать?

Нет, здесь всё правильно.

См.: [Фрагменты с ключами](https://ru.reactjs.org/docs/fragments.html#keyed-fragments) и [\<Fragment>](https://react.dev/reference/react/Fragment#props)
> optional `key`: Fragments declared with the _explicit_ `<Fragment>` syntax may have [keys](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key).

Это я напутал с местом для замечания, исходя из [предположения про использование фрагмента для компонентов](https://github.com/htmlacademy-react/96091-six-cities-12/pull/5#discussion_r1149851328).

2023-04-05 18:00 UTC, merged

2023-04-05 18:00 UTC, AlexMasterov commented on project/src/components/offer-card-nearby/offer-card-nearby.tsx
> +        null}
Ответил в ТГ.

2023-04-06 12:11 UTC, SergViktKobzev commented on project/src/components/offer-card-city/offer-card-city.tsx
> +    <article onMouseOver={offerCardMouseOverHandler} className="cities__card place-card">
А вообще на практике в реальной коммерческой разработке в каких случаях какие названия обработчиков используют (я имею ввиду какие приставки используют on, handle или handler)? Никак не могу уяснить

2023-04-07 00:46 UTC, AlexMasterov commented on project/src/components/offer-card-city/offer-card-city.tsx
> +    <article onMouseOver={offerCardMouseOverHandler} className="cities__card place-card">
```jsx
<article onMouseOver={handleMouseOver}>
```